name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List all changed files
        run: |
            var=${{ steps.changed-files.outputs.all_changed_files }}

            # Split the string by space
            IFS=' ' read -ra segments <<< "$var"

            # Initialize an empty array for last words
            last_words=()

            # Loop through the segments and extract the last word without extension
            for segment in "${segments[@]}"; do
                # Extract the last word without extension
                last_word=$(basename "$segment" | sed 's/\.[^.]*$//')

                # Add the last word to the array
                last_words+=("$last_word")
            done
            
            # Join the array elements with commas
            result=$(IFS=,; echo "${last_words[*]}")

            echo "Final result: $result"