name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-queue@v1

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        

      - name: List all changed files
        run: |
            # Initialize an empty array for last words
            last_words=()

            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                # Extract the last word without extension
                last_word=$(basename "$file" | sed 's/\.[^.]*$//')

                # Add the last word to the array
                last_words+=("$last_word")
            done

            # Join the array elements with commas
            result=$(IFS=,; echo "${last_words[*]}")

            echo "Final result: $result"
      - name: run loop
        run: |
            sleep 100

            
